********************************************************************************
* Variable Names of the Anonymous STULA2016
********************************************************************************
local   ListQVars ///
		GvmtStatsCode ///
		KanriCode ///
		SurveyYear ///
		SurveyType ///
		SerialNumRecord ///
		SerialNumHH ///
		SerialNumHHMem ///
		SingleHH ///
		ThreeMajorUrbanArea ///
		KWeight ///
		QSex ///
		QRelRes ///
		QCAgeRes ///
		QMarStatRes ///
		QEduRes ///
		QSubHealth ///
		QCoresFam65Nursing ///
		QProxCoresidFam65Nursing ///
		QLivSepFam65Nursing ///
		QCoresOthersNursing ///
		QProxCoresidOthersNursing ///
		QLivSepOthersNursing ///
		QNoneNursing ///
		QJobStat ///
		QDsrWork ///
		QDsrWorkHoursWeekUnemp ///
		QEmpStat ///
		QEmpFulltimeFlex ///
		QNofPaidLeaveTaken ///
		KJob ///
		QJobSize ///
		QWorkHoursWeek ///
		QDsrWorkHoursWeekEmp ///
		QAnnInc ///
		QHouseType ///
		QPrivCar ///
		QHHInc ///
		QReceiveCare ///
		QUnaccAssignment ///
		QUnaccAssignmentSpouse ///
		QUnaccAssignmentParent ///
		QUnaccAssignmentChild ///
		QUnaccAssignmentOthers ///
		QHosp ///
		QHospSpouse ///
		QHospParent ///
		QHospChild ///
		QHospOthers ///
		QRelHHpsnU10_1 ///
		QCAgeHHpsnU10_1 ///
		QSchoolHHpsnU10_1 ///
		QChildcareGrdParHHpsnU10_1 ///
		QChildcareNeighborHHpsnU10_1 ///
		QChildcareOthersHHpsnU10_1 ///
		QChildcareNoneHHpsnU10_1 ///
		QRelHHpsnU10_2 ///
		QCAgeHHpsnU10_2 ///
		QSchoolHHpsnU10_2 ///
		QChildcareGrdParHHpsnU10_2 ///
		QChildcareNeighborHHpsnU10_2 ///
		QChildcareOthersHHpsnU10_2 ///
		QChildcareNoneHHpsnU10_2 ///
		QRelHHpsnU10_3 ///
		QCAgeHHpsnU10_3 ///
		QSchoolHHpsnU10_3 ///
		QChildcareGrdParHHpsnU10_3 ///
		QChildcareNeighborHHpsnU10_3 ///
		QChildcareOthersHHpsnU10_3 ///
		QChildcareNoneHHpsnU10_3 ///
		QRelHHpsnU10_4 ///
		QCAgeHHpsnU10_4 ///
		QSchoolHHpsnU10_4 ///
		QChildcareGrdParHHpsnU10_4 ///
		QChildcareNeighborHHpsnU10_4 ///
		QChildcareOthersHHpsnU10_4 ///
		QChildcareNoneHHpsnU10_4 ///
		QRelHHpsnU10_5 ///
		QCAgeHHpsnU10_5 ///
		QSchoolHHpsnU10_5 ///
		QChildcareGrdParHHpsnU10_5 ///
		QChildcareNeighborHHpsnU10_5 ///
		QChildcareOthersHHpsnU10_5 ///
		QChildcareNoneHHpsnU10_5 ///
		QRelHHpsnU10_6 ///
		QCAgeHHpsnU10_6 ///
		QSchoolHHpsnU10_6 ///
		QChildcareGrdParHHpsnU10_6 ///
		QChildcareNeighborHHpsnU10_6 ///
		QChildcareOthersHHpsnU10_6 ///
		QChildcareNoneHHpsnU10_6 ///
		QNofHHpsnOver10 ///
		QNofHHpsnUnder10 ///
		KLifeStage ///
		KHHType ///
		KDoubleInc ///
		KWrkHoursWH4grp ///
		QHaveChild ///
		QHaveChildU6 ///
		QNofChildU6 ///
		QEduChildU6 ///
		KCAgeNatYg ///
		KEduNatYg ///
		QFstSndDay ///
		QDateRec ///
		QDayNoteTrip ///
		QDayNotePicnic ///
		QDayNoteCeremony ///
		QDayNoteWorkHome ///
		QDayNoteResting ///
		QDayNoteDayoff ///
		QDayNoteChildcareLeave ///
		QDayNoteNursingLeave ///
		QDayNoteOthers ///
		QWeather ///
		QDayWeek ///
		QActTypeAll ///
		QAllTotal ///
		QAllAlone ///
		QAllAloneExcSleep ///
		QAllFamily ///
		QAllColleague ///
		QAllOthers ///
		QAllUK ///
		QActTypeAllExcSleep ///
		QAllExcSleepTotal ///
		QAllExcSleepAlone ///
		QAllExcSleepAloneExcSleep ///
		QAllExcSleepFamily ///
		QAllExcSleepColleague ///
		QAllExcSleepOthers ///
		QAllExcSleepUK ///
		QActTypeSleep ///
		QSleepTotal ///
		QSleepAlone ///
		QSleepAloneExcSleep ///
		QSleepFamily ///
		QSleepColleague ///
		QSleepOthers ///
		QSleepUK ///
		QActTypePersonalCare ///
		QPersonalCareTotal ///
		QPersonalCareAlone ///
		QPersonalCareAloneExcSleep ///
		QPersonalCareFamily ///
		QPersonalCareColleague ///
		QPersonalCareOthers ///
		QPersonalCareUK ///
		QActTypeMeal ///
		QMealTotal ///
		QMealAlone ///
		QMealAloneExcSleep ///
		QMealFamily ///
		QMeaColleague ///
		QMealOthers ///
		QMealUK ///
		QActTypeCommute ///
		QCommuteTotal ///
		QCommuteAlone ///
		QCommuteAloneExcSleep ///
		QCommuteFamily ///
		QCommuteColleague ///
		QCommuteOthers ///
		QCommuteUK ///
		QActTypeWork ///
		QWorkTotal ///
		QWorkAlone ///
		QWorkAloneExcSleep ///
		QWorkFamily ///
		QWorkColleague ///
		QWorkOthers ///
		QWorkUK ///
		QActTypeSchoolWork ///
		QSchoolWorkTotal ///
		QSchoolWorkAlone ///
		QSchoolWorkAloneExcSleep ///
		QSchoolWorkFamily ///
		QSchoolWorkColleague ///
		QSchoolWorkOthers ///
		QSchoolWorkUK ///
		QActTypeHousekeeping ///
		QHousekeepingTotal ///
		QHousekeepingAlone ///
		QHousekeepingAloneExcSleep ///
		QHousekeepingFamily ///
		QHousekeepingColleague ///
		QHousekeepingOthers ///
		QHousekeepingUK ///
		QActTypeNursing ///
		QNursingTotal ///
		QNursingAlone ///
		QNursingAloneExcSleep ///
		QNursingFamily ///
		QNursingColleague ///
		QNursingOthers ///
		QNursingUK ///
		QActTypeChildcare ///
		QChildcareTotal ///
		QChildcareAlone ///
		QChildcareAloneExcSleep ///
		QChildcareFamily ///
		QChildcareColleague ///
		QChildcareOthers ///
		QChildcareUK ///
		QActTypeShopping ///
		QShoppingTotal ///
		QShoppingAlone ///
		QShoppingAloneExcSleep ///
		QShoppingFamily ///
		QShoppingColleague ///
		QShoppingOthers ///
		QShoppingUK ///
		QActTypeTravel ///
		QTravelTotal ///
		QTravelAlone ///
		QTravelAloneExcSleep ///
		QTravelFamily ///
		QTravelColleague ///
		QTravelOthers ///
		QTravelUK ///
		QActTypeTVRadioNewsMag ///
		QTVRadioNewsMagTotal ///
		QTVRadioNewsMagAlone ///
		QTVRadioNewsMagAloneExcSleep ///
		QTVRadioNewsMagFamily ///
		QTVRadioNewsMagColleague ///
		QTVRadioNewsMagOthers ///
		QTVRadioNewsMagUK ///
		QActTypeResting ///
		QRestingTotal ///
		QRestingAlone ///
		QRestingAloneExcSleep ///
		QRestingFamily ///
		QRestingColleague ///
		QRestingOthers ///
		QRestingUK ///
		QActTypeStudy ///
		QStudyTotal ///
		QStudyAlone ///
		QStudyAloneExcSleep ///
		QStudyFamily ///
		QStudyColleague ///
		QStudyOthers ///
		QStudyUK ///
		QActTypeLeisure ///
		QLeisureTotal ///
		QLeisureAlone ///
		QLeisureAloneExcSleep ///
		QLeisureFamily ///
		QLeisureColleague ///
		QLeisureOthers ///
		QLeisureUK ///
		QActTypeSports ///
		QSportsTotal ///
		QSportsAlone ///
		QSportsAloneExcSleep ///
		QSportsFamily ///
		QSportsColleague ///
		QSportsOthers ///
		QSportsUK ///
		QActTypeSocialAct ///
		QSocialActTotal ///
		QSocialActAlone ///
		QSocialActAloneExcSleep ///
		QSocialActFamily ///
		QSocialActColleague ///
		QSocialActOthers ///
		QSocialActUK ///
		QActTypeSocialLife ///
		QSocialLifeTotal ///
		QSocialLifeAlone ///
		QSocialLifeAloneExcSleep ///
		QSocialLifeFamily ///
		QSocialLifeColleague ///
		QSocialLifeOthers ///
		QSocialLifeUK ///
		QActTypeMedTreat ///
		QMedTreatTotal ///
		QMedTreatAlone ///
		QMedTreatAloneExcSleep ///
		QMedTreatFamily ///
		QMedTreatColleague ///
		QMedTreatOthers ///
		QMedTreatUK ///
		QActTypeOthers ///
		QOthersTotal ///
		QOthersAlone ///
		QOthersAloneExcSleep ///
		QOthersFamily ///
		QOthersColleague ///
		QOthersOthers ///
		QOthersUK ///
		QActTypePaidHouseWrk ///
		QPaidHouseWrkTotal ///
		QPaidHouseWrkAlone ///
		QPaidHouseWrkAloneExcSleep ///
		QPaidHouseWrkFamily ///
		QPaidHouseWrkColleague ///
		QPaidHouseWrkOthers ///
		QPaidHouseWrkUK ///
		QActTypePaidWrk ///
		QPaidWrkTotal ///
		QPaidWrkAlone ///
		QPaidWrkAloneExcSleep ///
		QPaidWrkFamily ///
		QPaidWrkColleague ///
		QPaidWrkOthers ///
		QPaidWrkUK ///
		QActTypeHouseWrk ///
		QHouseWrkTotal ///
		QHouseWrkAlone ///
		QHouseWrkAloneExcSleep ///
		QHouseWrkFamily ///
		QHouseWrkColleague ///
		QHouseWrkOthers ///
		QHouseWrkUK ///
		QActTypeFst ///
		QFstActTotal ///
		QFstActAlone ///
		QFstActAloneExcSleep ///
		QFstActFamily ///
		QFstActColleague ///
		QFstActOthers ///
		QFstActUK ///
		QActTypeFstExcSleep ///
		QFstExcSleepTotal ///
		QFstExcSleepAlone ///
		QFstExcSleepAloneExcSleep ///
		QFstExcSleepFamily ///
		QFstExcSleepColleague ///
		QFstExcSleepOthers ///
		QFstExcSleepUK ///
		QActTypeSnd ///
		QSndActTotal ///
		QSndActAlone ///
		QSndActAloneExcSleep ///
		QSndActFamily ///
		QSndActColleague ///
		QSndActOthers ///
		QSndActUK ///
		QActTypeTrd ///
		QTrdActTotal ///
		QTrdActAlone ///
		QTrdActAloneExcSleep ///
		QTrdActFamily ///
		QTrdActColleague ///
		QTrdActOthers ///
		QTrdActUK ///
		QTime1 ///
		QActType1 ///
		QTimeAlone1 ///
		QTimeFamily1 ///
		QTimeColleague1 ///
		QTimeOthers1 ///
		QTimeCompUse1 ///
		QCompUse1 ///
		QCompUseShopping1 ///
		QCompUseLeisure1 ///
		QCompUseCom1 ///
		QCompUseComFam1 ///
		QCompUseComFrnd1 ///
		QCompUseComOthers1 ///
		QCompUseOthers1 ///
		QTime2 ///
		QActType2 ///
		QTimeAlone2 ///
		QTimeFamily2 ///
		QTimeColleague2 ///
		QTimeOthers2 ///
		QTimeCompUse2 ///
		QCompUse2 ///
		QCompUseShopping2 ///
		QCompUseLeisure2 ///
		QCompUseCom2 ///
		QCompUseComFam2 ///
		QCompUseComFrnd2 ///
		QCompUseComOthers2 ///
		QCompUseOthers2 ///
		QTime3 ///
		QActType3 ///
		QTimeAlone3 ///
		QTimeFamily3 ///
		QTimeColleague3 ///
		QTimeOthers3 ///
		QTimeCompUse3 ///
		QCompUse3 ///
		QCompUseShopping3 ///
		QCompUseLeisure3 ///
		QCompUseCom3 ///
		QCompUseComFam3 ///
		QCompUseComFrnd3 ///
		QCompUseComOthers3 ///
		QCompUseOthers3 ///
		QTime4 ///
		QActType4 ///
		QTimeAlone4 ///
		QTimeFamily4 ///
		QTimeColleague4 ///
		QTimeOthers4 ///
		QTimeCompUse4 ///
		QCompUse4 ///
		QCompUseShopping4 ///
		QCompUseLeisure4 ///
		QCompUseCom4 ///
		QCompUseComFam4 ///
		QCompUseComFrnd4 ///
		QCompUseComOthers4 ///
		QCompUseOthers4 ///
		QTime5 ///
		QActType5 ///
		QTimeAlone5 ///
		QTimeFamily5 ///
		QTimeColleague5 ///
		QTimeOthers5 ///
		QTimeCompUse5 ///
		QCompUse5 ///
		QCompUseShopping5 ///
		QCompUseLeisure5 ///
		QCompUseCom5 ///
		QCompUseComFam5 ///
		QCompUseComFrnd5 ///
		QCompUseComOthers5 ///
		QCompUseOthers5 ///
		QTime6 ///
		QActType6 ///
		QTimeAlone6 ///
		QTimeFamily6 ///
		QTimeColleague6 ///
		QTimeOthers6 ///
		QTimeCompUse6 ///
		QCompUse6 ///
		QCompUseShopping6 ///
		QCompUseLeisure6 ///
		QCompUseCom6 ///
		QCompUseComFam6 ///
		QCompUseComFrnd6 ///
		QCompUseComOthers6 ///
		QCompUseOthers6 ///
		QTime7 ///
		QActType7 ///
		QTimeAlone7 ///
		QTimeFamily7 ///
		QTimeColleague7 ///
		QTimeOthers7 ///
		QTimeCompUse7 ///
		QCompUse7 ///
		QCompUseShopping7 ///
		QCompUseLeisure7 ///
		QCompUseCom7 ///
		QCompUseComFam7 ///
		QCompUseComFrnd7 ///
		QCompUseComOthers7 ///
		QCompUseOthers7 ///
		QTime8 ///
		QActType8 ///
		QTimeAlone8 ///
		QTimeFamily8 ///
		QTimeColleague8 ///
		QTimeOthers8 ///
		QTimeCompUse8 ///
		QCompUse8 ///
		QCompUseShopping8 ///
		QCompUseLeisure8 ///
		QCompUseCom8 ///
		QCompUseComFam8 ///
		QCompUseComFrnd8 ///
		QCompUseComOthers8 ///
		QCompUseOthers8 ///
		QTime9 ///
		QActType9 ///
		QTimeAlone9 ///
		QTimeFamily9 ///
		QTimeColleague9 ///
		QTimeOthers9 ///
		QTimeCompUse9 ///
		QCompUse9 ///
		QCompUseShopping9 ///
		QCompUseLeisure9 ///
		QCompUseCom9 ///
		QCompUseComFam9 ///
		QCompUseComFrnd9 ///
		QCompUseComOthers9 ///
		QCompUseOthers9 ///
		QTime10 ///
		QActType10 ///
		QTimeAlone10 ///
		QTimeFamily10 ///
		QTimeColleague10 ///
		QTimeOthers10 ///
		QTimeCompUse10 ///
		QCompUse10 ///
		QCompUseShopping10 ///
		QCompUseLeisure10 ///
		QCompUseCom10 ///
		QCompUseComFam10 ///
		QCompUseComFrnd10 ///
		QCompUseComOthers10 ///
		QCompUseOthers10 ///
		QTime11 ///
		QActType11 ///
		QTimeAlone11 ///
		QTimeFamily11 ///
		QTimeColleague11 ///
		QTimeOthers11 ///
		QTimeCompUse11 ///
		QCompUse11 ///
		QCompUseShopping11 ///
		QCompUseLeisure11 ///
		QCompUseCom11 ///
		QCompUseComFam11 ///
		QCompUseComFrnd11 ///
		QCompUseComOthers11 ///
		QCompUseOthers11 ///
		QTime12 ///
		QActType12 ///
		QTimeAlone12 ///
		QTimeFamily12 ///
		QTimeColleague12 ///
		QTimeOthers12 ///
		QTimeCompUse12 ///
		QCompUse12 ///
		QCompUseShopping12 ///
		QCompUseLeisure12 ///
		QCompUseCom12 ///
		QCompUseComFam12 ///
		QCompUseComFrnd12 ///
		QCompUseComOthers12 ///
		QCompUseOthers12 ///
		QTime13 ///
		QActType13 ///
		QTimeAlone13 ///
		QTimeFamily13 ///
		QTimeColleague13 ///
		QTimeOthers13 ///
		QTimeCompUse13 ///
		QCompUse13 ///
		QCompUseShopping13 ///
		QCompUseLeisure13 ///
		QCompUseCom13 ///
		QCompUseComFam13 ///
		QCompUseComFrnd13 ///
		QCompUseComOthers13 ///
		QCompUseOthers13 ///
		QTime14 ///
		QActType14 ///
		QTimeAlone14 ///
		QTimeFamily14 ///
		QTimeColleague14 ///
		QTimeOthers14 ///
		QTimeCompUse14 ///
		QCompUse14 ///
		QCompUseShopping14 ///
		QCompUseLeisure14 ///
		QCompUseCom14 ///
		QCompUseComFam14 ///
		QCompUseComFrnd14 ///
		QCompUseComOthers14 ///
		QCompUseOthers14 ///
		QTime15 ///
		QActType15 ///
		QTimeAlone15 ///
		QTimeFamily15 ///
		QTimeColleague15 ///
		QTimeOthers15 ///
		QTimeCompUse15 ///
		QCompUse15 ///
		QCompUseShopping15 ///
		QCompUseLeisure15 ///
		QCompUseCom15 ///
		QCompUseComFam15 ///
		QCompUseComFrnd15 ///
		QCompUseComOthers15 ///
		QCompUseOthers15 ///
		QTime16 ///
		QActType16 ///
		QTimeAlone16 ///
		QTimeFamily16 ///
		QTimeColleague16 ///
		QTimeOthers16 ///
		QTimeCompUse16 ///
		QCompUse16 ///
		QCompUseShopping16 ///
		QCompUseLeisure16 ///
		QCompUseCom16 ///
		QCompUseComFam16 ///
		QCompUseComFrnd16 ///
		QCompUseComOthers16 ///
		QCompUseOthers16 ///
		QTime17 ///
		QActType17 ///
		QTimeAlone17 ///
		QTimeFamily17 ///
		QTimeColleague17 ///
		QTimeOthers17 ///
		QTimeCompUse17 ///
		QCompUse17 ///
		QCompUseShopping17 ///
		QCompUseLeisure17 ///
		QCompUseCom17 ///
		QCompUseComFam17 ///
		QCompUseComFrnd17 ///
		QCompUseComOthers17 ///
		QCompUseOthers17 ///
		QTime18 ///
		QActType18 ///
		QTimeAlone18 ///
		QTimeFamily18 ///
		QTimeColleague18 ///
		QTimeOthers18 ///
		QTimeCompUse18 ///
		QCompUse18 ///
		QCompUseShopping18 ///
		QCompUseLeisure18 ///
		QCompUseCom18 ///
		QCompUseComFam18 ///
		QCompUseComFrnd18 ///
		QCompUseComOthers18 ///
		QCompUseOthers18 ///
		QTime19 ///
		QActType19 ///
		QTimeAlone19 ///
		QTimeFamily19 ///
		QTimeColleague19 ///
		QTimeOthers19 ///
		QTimeCompUse19 ///
		QCompUse19 ///
		QCompUseShopping19 ///
		QCompUseLeisure19 ///
		QCompUseCom19 ///
		QCompUseComFam19 ///
		QCompUseComFrnd19 ///
		QCompUseComOthers19 ///
		QCompUseOthers19 ///
		QTime20 ///
		QActType20 ///
		QTimeAlone20 ///
		QTimeFamily20 ///
		QTimeColleague20 ///
		QTimeOthers20 ///
		QTimeCompUse20 ///
		QCompUse20 ///
		QCompUseShopping20 ///
		QCompUseLeisure20 ///
		QCompUseCom20 ///
		QCompUseComFam20 ///
		QCompUseComFrnd20 ///
		QCompUseComOthers20 ///
		QCompUseOthers20 ///
		QTime21 ///
		QActType21 ///
		QTimeAlone21 ///
		QTimeFamily21 ///
		QTimeColleague21 ///
		QTimeOthers21 ///
		QTimeCompUse21 ///
		QCompUse21 ///
		QCompUseShopping21 ///
		QCompUseLeisure21 ///
		QCompUseCom21 ///
		QCompUseComFam21 ///
		QCompUseComFrnd21 ///
		QCompUseComOthers21 ///
		QCompUseOthers21 ///
		QTime22 ///
		QActType22 ///
		QTimeAlone22 ///
		QTimeFamily22 ///
		QTimeColleague22 ///
		QTimeOthers22 ///
		QTimeCompUse22 ///
		QCompUse22 ///
		QCompUseShopping22 ///
		QCompUseLeisure22 ///
		QCompUseCom22 ///
		QCompUseComFam22 ///
		QCompUseComFrnd22 ///
		QCompUseComOthers22 ///
		QCompUseOthers22 ///
		QTime23 ///
		QActType23 ///
		QTimeAlone23 ///
		QTimeFamily23 ///
		QTimeColleague23 ///
		QTimeOthers23 ///
		QTimeCompUse23 ///
		QCompUse23 ///
		QCompUseShopping23 ///
		QCompUseLeisure23 ///
		QCompUseCom23 ///
		QCompUseComFam23 ///
		QCompUseComFrnd23 ///
		QCompUseComOthers23 ///
		QCompUseOthers23 ///
		QTime24 ///
		QActType24 ///
		QTimeAlone24 ///
		QTimeFamily24 ///
		QTimeColleague24 ///
		QTimeOthers24 ///
		QTimeCompUse24 ///
		QCompUse24 ///
		QCompUseShopping24 ///
		QCompUseLeisure24 ///
		QCompUseCom24 ///
		QCompUseComFam24 ///
		QCompUseComFrnd24 ///
		QCompUseComOthers24 ///
		QCompUseOthers24 ///
		QTime25 ///
		QActType25 ///
		QTimeAlone25 ///
		QTimeFamily25 ///
		QTimeColleague25 ///
		QTimeOthers25 ///
		QTimeCompUse25 ///
		QCompUse25 ///
		QCompUseShopping25 ///
		QCompUseLeisure25 ///
		QCompUseCom25 ///
		QCompUseComFam25 ///
		QCompUseComFrnd25 ///
		QCompUseComOthers25 ///
		QCompUseOthers25 ///
		QTime26 ///
		QActType26 ///
		QTimeAlone26 ///
		QTimeFamily26 ///
		QTimeColleague26 ///
		QTimeOthers26 ///
		QTimeCompUse26 ///
		QCompUse26 ///
		QCompUseShopping26 ///
		QCompUseLeisure26 ///
		QCompUseCom26 ///
		QCompUseComFam26 ///
		QCompUseComFrnd26 ///
		QCompUseComOthers26 ///
		QCompUseOthers26 ///
		QTime27 ///
		QActType27 ///
		QTimeAlone27 ///
		QTimeFamily27 ///
		QTimeColleague27 ///
		QTimeOthers27 ///
		QTimeCompUse27 ///
		QCompUse27 ///
		QCompUseShopping27 ///
		QCompUseLeisure27 ///
		QCompUseCom27 ///
		QCompUseComFam27 ///
		QCompUseComFrnd27 ///
		QCompUseComOthers27 ///
		QCompUseOthers27 ///
		QTime28 ///
		QActType28 ///
		QTimeAlone28 ///
		QTimeFamily28 ///
		QTimeColleague28 ///
		QTimeOthers28 ///
		QTimeCompUse28 ///
		QCompUse28 ///
		QCompUseShopping28 ///
		QCompUseLeisure28 ///
		QCompUseCom28 ///
		QCompUseComFam28 ///
		QCompUseComFrnd28 ///
		QCompUseComOthers28 ///
		QCompUseOthers28 ///
		QTime29 ///
		QActType29 ///
		QTimeAlone29 ///
		QTimeFamily29 ///
		QTimeColleague29 ///
		QTimeOthers29 ///
		QTimeCompUse29 ///
		QCompUse29 ///
		QCompUseShopping29 ///
		QCompUseLeisure29 ///
		QCompUseCom29 ///
		QCompUseComFam29 ///
		QCompUseComFrnd29 ///
		QCompUseComOthers29 ///
		QCompUseOthers29 ///
		QTime30 ///
		QActType30 ///
		QTimeAlone30 ///
		QTimeFamily30 ///
		QTimeColleague30 ///
		QTimeOthers30 ///
		QTimeCompUse30 ///
		QCompUse30 ///
		QCompUseShopping30 ///
		QCompUseLeisure30 ///
		QCompUseCom30 ///
		QCompUseComFam30 ///
		QCompUseComFrnd30 ///
		QCompUseComOthers30 ///
		QCompUseOthers30 ///
		QTime31 ///
		QActType31 ///
		QTimeAlone31 ///
		QTimeFamily31 ///
		QTimeColleague31 ///
		QTimeOthers31 ///
		QTimeCompUse31 ///
		QCompUse31 ///
		QCompUseShopping31 ///
		QCompUseLeisure31 ///
		QCompUseCom31 ///
		QCompUseComFam31 ///
		QCompUseComFrnd31 ///
		QCompUseComOthers31 ///
		QCompUseOthers31 ///
		QTime32 ///
		QActType32 ///
		QTimeAlone32 ///
		QTimeFamily32 ///
		QTimeColleague32 ///
		QTimeOthers32 ///
		QTimeCompUse32 ///
		QCompUse32 ///
		QCompUseShopping32 ///
		QCompUseLeisure32 ///
		QCompUseCom32 ///
		QCompUseComFam32 ///
		QCompUseComFrnd32 ///
		QCompUseComOthers32 ///
		QCompUseOthers32 ///
		QTime33 ///
		QActType33 ///
		QTimeAlone33 ///
		QTimeFamily33 ///
		QTimeColleague33 ///
		QTimeOthers33 ///
		QTimeCompUse33 ///
		QCompUse33 ///
		QCompUseShopping33 ///
		QCompUseLeisure33 ///
		QCompUseCom33 ///
		QCompUseComFam33 ///
		QCompUseComFrnd33 ///
		QCompUseComOthers33 ///
		QCompUseOthers33 ///
		QTime34 ///
		QActType34 ///
		QTimeAlone34 ///
		QTimeFamily34 ///
		QTimeColleague34 ///
		QTimeOthers34 ///
		QTimeCompUse34 ///
		QCompUse34 ///
		QCompUseShopping34 ///
		QCompUseLeisure34 ///
		QCompUseCom34 ///
		QCompUseComFam34 ///
		QCompUseComFrnd34 ///
		QCompUseComOthers34 ///
		QCompUseOthers34 ///
		QTime35 ///
		QActType35 ///
		QTimeAlone35 ///
		QTimeFamily35 ///
		QTimeColleague35 ///
		QTimeOthers35 ///
		QTimeCompUse35 ///
		QCompUse35 ///
		QCompUseShopping35 ///
		QCompUseLeisure35 ///
		QCompUseCom35 ///
		QCompUseComFam35 ///
		QCompUseComFrnd35 ///
		QCompUseComOthers35 ///
		QCompUseOthers35 ///
		QTime36 ///
		QActType36 ///
		QTimeAlone36 ///
		QTimeFamily36 ///
		QTimeColleague36 ///
		QTimeOthers36 ///
		QTimeCompUse36 ///
		QCompUse36 ///
		QCompUseShopping36 ///
		QCompUseLeisure36 ///
		QCompUseCom36 ///
		QCompUseComFam36 ///
		QCompUseComFrnd36 ///
		QCompUseComOthers36 ///
		QCompUseOthers36 ///
		QTime37 ///
		QActType37 ///
		QTimeAlone37 ///
		QTimeFamily37 ///
		QTimeColleague37 ///
		QTimeOthers37 ///
		QTimeCompUse37 ///
		QCompUse37 ///
		QCompUseShopping37 ///
		QCompUseLeisure37 ///
		QCompUseCom37 ///
		QCompUseComFam37 ///
		QCompUseComFrnd37 ///
		QCompUseComOthers37 ///
		QCompUseOthers37 ///
		QTime38 ///
		QActType38 ///
		QTimeAlone38 ///
		QTimeFamily38 ///
		QTimeColleague38 ///
		QTimeOthers38 ///
		QTimeCompUse38 ///
		QCompUse38 ///
		QCompUseShopping38 ///
		QCompUseLeisure38 ///
		QCompUseCom38 ///
		QCompUseComFam38 ///
		QCompUseComFrnd38 ///
		QCompUseComOthers38 ///
		QCompUseOthers38 ///
		QTime39 ///
		QActType39 ///
		QTimeAlone39 ///
		QTimeFamily39 ///
		QTimeColleague39 ///
		QTimeOthers39 ///
		QTimeCompUse39 ///
		QCompUse39 ///
		QCompUseShopping39 ///
		QCompUseLeisure39 ///
		QCompUseCom39 ///
		QCompUseComFam39 ///
		QCompUseComFrnd39 ///
		QCompUseComOthers39 ///
		QCompUseOthers39 ///
		QTime40 ///
		QActType40 ///
		QTimeAlone40 ///
		QTimeFamily40 ///
		QTimeColleague40 ///
		QTimeOthers40 ///
		QTimeCompUse40 ///
		QCompUse40 ///
		QCompUseShopping40 ///
		QCompUseLeisure40 ///
		QCompUseCom40 ///
		QCompUseComFam40 ///
		QCompUseComFrnd40 ///
		QCompUseComOthers40 ///
		QCompUseOthers40 ///
		QTime41 ///
		QActType41 ///
		QTimeAlone41 ///
		QTimeFamily41 ///
		QTimeColleague41 ///
		QTimeOthers41 ///
		QTimeCompUse41 ///
		QCompUse41 ///
		QCompUseShopping41 ///
		QCompUseLeisure41 ///
		QCompUseCom41 ///
		QCompUseComFam41 ///
		QCompUseComFrnd41 ///
		QCompUseComOthers41 ///
		QCompUseOthers41 ///
		QTime42 ///
		QActType42 ///
		QTimeAlone42 ///
		QTimeFamily42 ///
		QTimeColleague42 ///
		QTimeOthers42 ///
		QTimeCompUse42 ///
		QCompUse42 ///
		QCompUseShopping42 ///
		QCompUseLeisure42 ///
		QCompUseCom42 ///
		QCompUseComFam42 ///
		QCompUseComFrnd42 ///
		QCompUseComOthers42 ///
		QCompUseOthers42 ///
		QTime43 ///
		QActType43 ///
		QTimeAlone43 ///
		QTimeFamily43 ///
		QTimeColleague43 ///
		QTimeOthers43 ///
		QTimeCompUse43 ///
		QCompUse43 ///
		QCompUseShopping43 ///
		QCompUseLeisure43 ///
		QCompUseCom43 ///
		QCompUseComFam43 ///
		QCompUseComFrnd43 ///
		QCompUseComOthers43 ///
		QCompUseOthers43 ///
		QTime44 ///
		QActType44 ///
		QTimeAlone44 ///
		QTimeFamily44 ///
		QTimeColleague44 ///
		QTimeOthers44 ///
		QTimeCompUse44 ///
		QCompUse44 ///
		QCompUseShopping44 ///
		QCompUseLeisure44 ///
		QCompUseCom44 ///
		QCompUseComFam44 ///
		QCompUseComFrnd44 ///
		QCompUseComOthers44 ///
		QCompUseOthers44 ///
		QTime45 ///
		QActType45 ///
		QTimeAlone45 ///
		QTimeFamily45 ///
		QTimeColleague45 ///
		QTimeOthers45 ///
		QTimeCompUse45 ///
		QCompUse45 ///
		QCompUseShopping45 ///
		QCompUseLeisure45 ///
		QCompUseCom45 ///
		QCompUseComFam45 ///
		QCompUseComFrnd45 ///
		QCompUseComOthers45 ///
		QCompUseOthers45 ///
		QTime46 ///
		QActType46 ///
		QTimeAlone46 ///
		QTimeFamily46 ///
		QTimeColleague46 ///
		QTimeOthers46 ///
		QTimeCompUse46 ///
		QCompUse46 ///
		QCompUseShopping46 ///
		QCompUseLeisure46 ///
		QCompUseCom46 ///
		QCompUseComFam46 ///
		QCompUseComFrnd46 ///
		QCompUseComOthers46 ///
		QCompUseOthers46 ///
		QTime47 ///
		QActType47 ///
		QTimeAlone47 ///
		QTimeFamily47 ///
		QTimeColleague47 ///
		QTimeOthers47 ///
		QTimeCompUse47 ///
		QCompUse47 ///
		QCompUseShopping47 ///
		QCompUseLeisure47 ///
		QCompUseCom47 ///
		QCompUseComFam47 ///
		QCompUseComFrnd47 ///
		QCompUseComOthers47 ///
		QCompUseOthers47 ///
		QTime48 ///
		QActType48 ///
		QTimeAlone48 ///
		QTimeFamily48 ///
		QTimeColleague48 ///
		QTimeOthers48 ///
		QTimeCompUse48 ///
		QCompUse48 ///
		QCompUseShopping48 ///
		QCompUseLeisure48 ///
		QCompUseCom48 ///
		QCompUseComFam48 ///
		QCompUseComFrnd48 ///
		QCompUseComOthers48 ///
		QCompUseOthers48 ///
		QTime49 ///
		QActType49 ///
		QTimeAlone49 ///
		QTimeFamily49 ///
		QTimeColleague49 ///
		QTimeOthers49 ///
		QTimeCompUse49 ///
		QCompUse49 ///
		QCompUseShopping49 ///
		QCompUseLeisure49 ///
		QCompUseCom49 ///
		QCompUseComFam49 ///
		QCompUseComFrnd49 ///
		QCompUseComOthers49 ///
		QCompUseOthers49 ///
		QTime50 ///
		QActType50 ///
		QTimeAlone50 ///
		QTimeFamily50 ///
		QTimeColleague50 ///
		QTimeOthers50 ///
		QTimeCompUse50 ///
		QCompUse50 ///
		QCompUseShopping50 ///
		QCompUseLeisure50 ///
		QCompUseCom50 ///
		QCompUseComFam50 ///
		QCompUseComFrnd50 ///
		QCompUseComOthers50 ///
		QCompUseOthers50 ///
		QTime51 ///
		QActType51 ///
		QTimeAlone51 ///
		QTimeFamily51 ///
		QTimeColleague51 ///
		QTimeOthers51 ///
		QTimeCompUse51 ///
		QCompUse51 ///
		QCompUseShopping51 ///
		QCompUseLeisure51 ///
		QCompUseCom51 ///
		QCompUseComFam51 ///
		QCompUseComFrnd51 ///
		QCompUseComOthers51 ///
		QCompUseOthers51 ///
		QTime52 ///
		QActType52 ///
		QTimeAlone52 ///
		QTimeFamily52 ///
		QTimeColleague52 ///
		QTimeOthers52 ///
		QTimeCompUse52 ///
		QCompUse52 ///
		QCompUseShopping52 ///
		QCompUseLeisure52 ///
		QCompUseCom52 ///
		QCompUseComFam52 ///
		QCompUseComFrnd52 ///
		QCompUseComOthers52 ///
		QCompUseOthers52 ///
		QTime53 ///
		QActType53 ///
		QTimeAlone53 ///
		QTimeFamily53 ///
		QTimeColleague53 ///
		QTimeOthers53 ///
		QTimeCompUse53 ///
		QCompUse53 ///
		QCompUseShopping53 ///
		QCompUseLeisure53 ///
		QCompUseCom53 ///
		QCompUseComFam53 ///
		QCompUseComFrnd53 ///
		QCompUseComOthers53 ///
		QCompUseOthers53 ///
		QTime54 ///
		QActType54 ///
		QTimeAlone54 ///
		QTimeFamily54 ///
		QTimeColleague54 ///
		QTimeOthers54 ///
		QTimeCompUse54 ///
		QCompUse54 ///
		QCompUseShopping54 ///
		QCompUseLeisure54 ///
		QCompUseCom54 ///
		QCompUseComFam54 ///
		QCompUseComFrnd54 ///
		QCompUseComOthers54 ///
		QCompUseOthers54 ///
		QTime55 ///
		QActType55 ///
		QTimeAlone55 ///
		QTimeFamily55 ///
		QTimeColleague55 ///
		QTimeOthers55 ///
		QTimeCompUse55 ///
		QCompUse55 ///
		QCompUseShopping55 ///
		QCompUseLeisure55 ///
		QCompUseCom55 ///
		QCompUseComFam55 ///
		QCompUseComFrnd55 ///
		QCompUseComOthers55 ///
		QCompUseOthers55 ///
		QTime56 ///
		QActType56 ///
		QTimeAlone56 ///
		QTimeFamily56 ///
		QTimeColleague56 ///
		QTimeOthers56 ///
		QTimeCompUse56 ///
		QCompUse56 ///
		QCompUseShopping56 ///
		QCompUseLeisure56 ///
		QCompUseCom56 ///
		QCompUseComFam56 ///
		QCompUseComFrnd56 ///
		QCompUseComOthers56 ///
		QCompUseOthers56 ///
		QTime57 ///
		QActType57 ///
		QTimeAlone57 ///
		QTimeFamily57 ///
		QTimeColleague57 ///
		QTimeOthers57 ///
		QTimeCompUse57 ///
		QCompUse57 ///
		QCompUseShopping57 ///
		QCompUseLeisure57 ///
		QCompUseCom57 ///
		QCompUseComFam57 ///
		QCompUseComFrnd57 ///
		QCompUseComOthers57 ///
		QCompUseOthers57 ///
		QTime58 ///
		QActType58 ///
		QTimeAlone58 ///
		QTimeFamily58 ///
		QTimeColleague58 ///
		QTimeOthers58 ///
		QTimeCompUse58 ///
		QCompUse58 ///
		QCompUseShopping58 ///
		QCompUseLeisure58 ///
		QCompUseCom58 ///
		QCompUseComFam58 ///
		QCompUseComFrnd58 ///
		QCompUseComOthers58 ///
		QCompUseOthers58 ///
		QTime59 ///
		QActType59 ///
		QTimeAlone59 ///
		QTimeFamily59 ///
		QTimeColleague59 ///
		QTimeOthers59 ///
		QTimeCompUse59 ///
		QCompUse59 ///
		QCompUseShopping59 ///
		QCompUseLeisure59 ///
		QCompUseCom59 ///
		QCompUseComFam59 ///
		QCompUseComFrnd59 ///
		QCompUseComOthers59 ///
		QCompUseOthers59 ///
		QTime60 ///
		QActType60 ///
		QTimeAlone60 ///
		QTimeFamily60 ///
		QTimeColleague60 ///
		QTimeOthers60 ///
		QTimeCompUse60 ///
		QCompUse60 ///
		QCompUseShopping60 ///
		QCompUseLeisure60 ///
		QCompUseCom60 ///
		QCompUseComFam60 ///
		QCompUseComFrnd60 ///
		QCompUseComOthers60 ///
		QCompUseOthers60 ///
		QTime61 ///
		QActType61 ///
		QTimeAlone61 ///
		QTimeFamily61 ///
		QTimeColleague61 ///
		QTimeOthers61 ///
		QTimeCompUse61 ///
		QCompUse61 ///
		QCompUseShopping61 ///
		QCompUseLeisure61 ///
		QCompUseCom61 ///
		QCompUseComFam61 ///
		QCompUseComFrnd61 ///
		QCompUseComOthers61 ///
		QCompUseOthers61 ///
		QTime62 ///
		QActType62 ///
		QTimeAlone62 ///
		QTimeFamily62 ///
		QTimeColleague62 ///
		QTimeOthers62 ///
		QTimeCompUse62 ///
		QCompUse62 ///
		QCompUseShopping62 ///
		QCompUseLeisure62 ///
		QCompUseCom62 ///
		QCompUseComFam62 ///
		QCompUseComFrnd62 ///
		QCompUseComOthers62 ///
		QCompUseOthers62 ///
		QTime63 ///
		QActType63 ///
		QTimeAlone63 ///
		QTimeFamily63 ///
		QTimeColleague63 ///
		QTimeOthers63 ///
		QTimeCompUse63 ///
		QCompUse63 ///
		QCompUseShopping63 ///
		QCompUseLeisure63 ///
		QCompUseCom63 ///
		QCompUseComFam63 ///
		QCompUseComFrnd63 ///
		QCompUseComOthers63 ///
		QCompUseOthers63 ///
		QTime64 ///
		QActType64 ///
		QTimeAlone64 ///
		QTimeFamily64 ///
		QTimeColleague64 ///
		QTimeOthers64 ///
		QTimeCompUse64 ///
		QCompUse64 ///
		QCompUseShopping64 ///
		QCompUseLeisure64 ///
		QCompUseCom64 ///
		QCompUseComFam64 ///
		QCompUseComFrnd64 ///
		QCompUseComOthers64 ///
		QCompUseOthers64 ///
		QTime65 ///
		QActType65 ///
		QTimeAlone65 ///
		QTimeFamily65 ///
		QTimeColleague65 ///
		QTimeOthers65 ///
		QTimeCompUse65 ///
		QCompUse65 ///
		QCompUseShopping65 ///
		QCompUseLeisure65 ///
		QCompUseCom65 ///
		QCompUseComFam65 ///
		QCompUseComFrnd65 ///
		QCompUseComOthers65 ///
		QCompUseOthers65 ///
		QTime66 ///
		QActType66 ///
		QTimeAlone66 ///
		QTimeFamily66 ///
		QTimeColleague66 ///
		QTimeOthers66 ///
		QTimeCompUse66 ///
		QCompUse66 ///
		QCompUseShopping66 ///
		QCompUseLeisure66 ///
		QCompUseCom66 ///
		QCompUseComFam66 ///
		QCompUseComFrnd66 ///
		QCompUseComOthers66 ///
		QCompUseOthers66 ///
		QTime67 ///
		QActType67 ///
		QTimeAlone67 ///
		QTimeFamily67 ///
		QTimeColleague67 ///
		QTimeOthers67 ///
		QTimeCompUse67 ///
		QCompUse67 ///
		QCompUseShopping67 ///
		QCompUseLeisure67 ///
		QCompUseCom67 ///
		QCompUseComFam67 ///
		QCompUseComFrnd67 ///
		QCompUseComOthers67 ///
		QCompUseOthers67 ///
		QTime68 ///
		QActType68 ///
		QTimeAlone68 ///
		QTimeFamily68 ///
		QTimeColleague68 ///
		QTimeOthers68 ///
		QTimeCompUse68 ///
		QCompUse68 ///
		QCompUseShopping68 ///
		QCompUseLeisure68 ///
		QCompUseCom68 ///
		QCompUseComFam68 ///
		QCompUseComFrnd68 ///
		QCompUseComOthers68 ///
		QCompUseOthers68 ///
		QTime69 ///
		QActType69 ///
		QTimeAlone69 ///
		QTimeFamily69 ///
		QTimeColleague69 ///
		QTimeOthers69 ///
		QTimeCompUse69 ///
		QCompUse69 ///
		QCompUseShopping69 ///
		QCompUseLeisure69 ///
		QCompUseCom69 ///
		QCompUseComFam69 ///
		QCompUseComFrnd69 ///
		QCompUseComOthers69 ///
		QCompUseOthers69 ///
		QTime70 ///
		QActType70 ///
		QTimeAlone70 ///
		QTimeFamily70 ///
		QTimeColleague70 ///
		QTimeOthers70 ///
		QTimeCompUse70 ///
		QCompUse70 ///
		QCompUseShopping70 ///
		QCompUseLeisure70 ///
		QCompUseCom70 ///
		QCompUseComFam70 ///
		QCompUseComFrnd70 ///
		QCompUseComOthers70 ///
		QCompUseOthers70 ///
		QTime71 ///
		QActType71 ///
		QTimeAlone71 ///
		QTimeFamily71 ///
		QTimeColleague71 ///
		QTimeOthers71 ///
		QTimeCompUse71 ///
		QCompUse71 ///
		QCompUseShopping71 ///
		QCompUseLeisure71 ///
		QCompUseCom71 ///
		QCompUseComFam71 ///
		QCompUseComFrnd71 ///
		QCompUseComOthers71 ///
		QCompUseOthers71 ///
		QTime72 ///
		QActType72 ///
		QTimeAlone72 ///
		QTimeFamily72 ///
		QTimeColleague72 ///
		QTimeOthers72 ///
		QTimeCompUse72 ///
		QCompUse72 ///
		QCompUseShopping72 ///
		QCompUseLeisure72 ///
		QCompUseCom72 ///
		QCompUseComFam72 ///
		QCompUseComFrnd72 ///
		QCompUseComOthers72 ///
		QCompUseOthers72 ///
		QTime73 ///
		QActType73 ///
		QTimeAlone73 ///
		QTimeFamily73 ///
		QTimeColleague73 ///
		QTimeOthers73 ///
		QTimeCompUse73 ///
		QCompUse73 ///
		QCompUseShopping73 ///
		QCompUseLeisure73 ///
		QCompUseCom73 ///
		QCompUseComFam73 ///
		QCompUseComFrnd73 ///
		QCompUseComOthers73 ///
		QCompUseOthers73 ///
		QTime74 ///
		QActType74 ///
		QTimeAlone74 ///
		QTimeFamily74 ///
		QTimeColleague74 ///
		QTimeOthers74 ///
		QTimeCompUse74 ///
		QCompUse74 ///
		QCompUseShopping74 ///
		QCompUseLeisure74 ///
		QCompUseCom74 ///
		QCompUseComFam74 ///
		QCompUseComFrnd74 ///
		QCompUseComOthers74 ///
		QCompUseOthers74 ///
		QTime75 ///
		QActType75 ///
		QTimeAlone75 ///
		QTimeFamily75 ///
		QTimeColleague75 ///
		QTimeOthers75 ///
		QTimeCompUse75 ///
		QCompUse75 ///
		QCompUseShopping75 ///
		QCompUseLeisure75 ///
		QCompUseCom75 ///
		QCompUseComFam75 ///
		QCompUseComFrnd75 ///
		QCompUseComOthers75 ///
		QCompUseOthers75 ///
		QTime76 ///
		QActType76 ///
		QTimeAlone76 ///
		QTimeFamily76 ///
		QTimeColleague76 ///
		QTimeOthers76 ///
		QTimeCompUse76 ///
		QCompUse76 ///
		QCompUseShopping76 ///
		QCompUseLeisure76 ///
		QCompUseCom76 ///
		QCompUseComFam76 ///
		QCompUseComFrnd76 ///
		QCompUseComOthers76 ///
		QCompUseOthers76 ///
		QTime77 ///
		QActType77 ///
		QTimeAlone77 ///
		QTimeFamily77 ///
		QTimeColleague77 ///
		QTimeOthers77 ///
		QTimeCompUse77 ///
		QCompUse77 ///
		QCompUseShopping77 ///
		QCompUseLeisure77 ///
		QCompUseCom77 ///
		QCompUseComFam77 ///
		QCompUseComFrnd77 ///
		QCompUseComOthers77 ///
		QCompUseOthers77 ///
		QTime78 ///
		QActType78 ///
		QTimeAlone78 ///
		QTimeFamily78 ///
		QTimeColleague78 ///
		QTimeOthers78 ///
		QTimeCompUse78 ///
		QCompUse78 ///
		QCompUseShopping78 ///
		QCompUseLeisure78 ///
		QCompUseCom78 ///
		QCompUseComFam78 ///
		QCompUseComFrnd78 ///
		QCompUseComOthers78 ///
		QCompUseOthers78 ///
		QTime79 ///
		QActType79 ///
		QTimeAlone79 ///
		QTimeFamily79 ///
		QTimeColleague79 ///
		QTimeOthers79 ///
		QTimeCompUse79 ///
		QCompUse79 ///
		QCompUseShopping79 ///
		QCompUseLeisure79 ///
		QCompUseCom79 ///
		QCompUseComFam79 ///
		QCompUseComFrnd79 ///
		QCompUseComOthers79 ///
		QCompUseOthers79 ///
		QTime80 ///
		QActType80 ///
		QTimeAlone80 ///
		QTimeFamily80 ///
		QTimeColleague80 ///
		QTimeOthers80 ///
		QTimeCompUse80 ///
		QCompUse80 ///
		QCompUseShopping80 ///
		QCompUseLeisure80 ///
		QCompUseCom80 ///
		QCompUseComFam80 ///
		QCompUseComFrnd80 ///
		QCompUseComOthers80 ///
		QCompUseOthers80 ///
		QTime81 ///
		QActType81 ///
		QTimeAlone81 ///
		QTimeFamily81 ///
		QTimeColleague81 ///
		QTimeOthers81 ///
		QTimeCompUse81 ///
		QCompUse81 ///
		QCompUseShopping81 ///
		QCompUseLeisure81 ///
		QCompUseCom81 ///
		QCompUseComFam81 ///
		QCompUseComFrnd81 ///
		QCompUseComOthers81 ///
		QCompUseOthers81 ///
		QTime82 ///
		QActType82 ///
		QTimeAlone82 ///
		QTimeFamily82 ///
		QTimeColleague82 ///
		QTimeOthers82 ///
		QTimeCompUse82 ///
		QCompUse82 ///
		QCompUseShopping82 ///
		QCompUseLeisure82 ///
		QCompUseCom82 ///
		QCompUseComFam82 ///
		QCompUseComFrnd82 ///
		QCompUseComOthers82 ///
		QCompUseOthers82 ///
		QTime83 ///
		QActType83 ///
		QTimeAlone83 ///
		QTimeFamily83 ///
		QTimeColleague83 ///
		QTimeOthers83 ///
		QTimeCompUse83 ///
		QCompUse83 ///
		QCompUseShopping83 ///
		QCompUseLeisure83 ///
		QCompUseCom83 ///
		QCompUseComFam83 ///
		QCompUseComFrnd83 ///
		QCompUseComOthers83 ///
		QCompUseOthers83 ///
		QTime84 ///
		QActType84 ///
		QTimeAlone84 ///
		QTimeFamily84 ///
		QTimeColleague84 ///
		QTimeOthers84 ///
		QTimeCompUse84 ///
		QCompUse84 ///
		QCompUseShopping84 ///
		QCompUseLeisure84 ///
		QCompUseCom84 ///
		QCompUseComFam84 ///
		QCompUseComFrnd84 ///
		QCompUseComOthers84 ///
		QCompUseOthers84 ///
		QTime85 ///
		QActType85 ///
		QTimeAlone85 ///
		QTimeFamily85 ///
		QTimeColleague85 ///
		QTimeOthers85 ///
		QTimeCompUse85 ///
		QCompUse85 ///
		QCompUseShopping85 ///
		QCompUseLeisure85 ///
		QCompUseCom85 ///
		QCompUseComFam85 ///
		QCompUseComFrnd85 ///
		QCompUseComOthers85 ///
		QCompUseOthers85 ///
		QTime86 ///
		QActType86 ///
		QTimeAlone86 ///
		QTimeFamily86 ///
		QTimeColleague86 ///
		QTimeOthers86 ///
		QTimeCompUse86 ///
		QCompUse86 ///
		QCompUseShopping86 ///
		QCompUseLeisure86 ///
		QCompUseCom86 ///
		QCompUseComFam86 ///
		QCompUseComFrnd86 ///
		QCompUseComOthers86 ///
		QCompUseOthers86 ///
		QTime87 ///
		QActType87 ///
		QTimeAlone87 ///
		QTimeFamily87 ///
		QTimeColleague87 ///
		QTimeOthers87 ///
		QTimeCompUse87 ///
		QCompUse87 ///
		QCompUseShopping87 ///
		QCompUseLeisure87 ///
		QCompUseCom87 ///
		QCompUseComFam87 ///
		QCompUseComFrnd87 ///
		QCompUseComOthers87 ///
		QCompUseOthers87 ///
		QTime88 ///
		QActType88 ///
		QTimeAlone88 ///
		QTimeFamily88 ///
		QTimeColleague88 ///
		QTimeOthers88 ///
		QTimeCompUse88 ///
		QCompUse88 ///
		QCompUseShopping88 ///
		QCompUseLeisure88 ///
		QCompUseCom88 ///
		QCompUseComFam88 ///
		QCompUseComFrnd88 ///
		QCompUseComOthers88 ///
		QCompUseOthers88 ///
		QTime89 ///
		QActType89 ///
		QTimeAlone89 ///
		QTimeFamily89 ///
		QTimeColleague89 ///
		QTimeOthers89 ///
		QTimeCompUse89 ///
		QCompUse89 ///
		QCompUseShopping89 ///
		QCompUseLeisure89 ///
		QCompUseCom89 ///
		QCompUseComFam89 ///
		QCompUseComFrnd89 ///
		QCompUseComOthers89 ///
		QCompUseOthers89 ///
		QTime90 ///
		QActType90 ///
		QTimeAlone90 ///
		QTimeFamily90 ///
		QTimeColleague90 ///
		QTimeOthers90 ///
		QTimeCompUse90 ///
		QCompUse90 ///
		QCompUseShopping90 ///
		QCompUseLeisure90 ///
		QCompUseCom90 ///
		QCompUseComFam90 ///
		QCompUseComFrnd90 ///
		QCompUseComOthers90 ///
		QCompUseOthers90 ///
		QTime91 ///
		QActType91 ///
		QTimeAlone91 ///
		QTimeFamily91 ///
		QTimeColleague91 ///
		QTimeOthers91 ///
		QTimeCompUse91 ///
		QCompUse91 ///
		QCompUseShopping91 ///
		QCompUseLeisure91 ///
		QCompUseCom91 ///
		QCompUseComFam91 ///
		QCompUseComFrnd91 ///
		QCompUseComOthers91 ///
		QCompUseOthers91 ///
		QTime92 ///
		QActType92 ///
		QTimeAlone92 ///
		QTimeFamily92 ///
		QTimeColleague92 ///
		QTimeOthers92 ///
		QTimeCompUse92 ///
		QCompUse92 ///
		QCompUseShopping92 ///
		QCompUseLeisure92 ///
		QCompUseCom92 ///
		QCompUseComFam92 ///
		QCompUseComFrnd92 ///
		QCompUseComOthers92 ///
		QCompUseOthers92 ///
		QTime93 ///
		QActType93 ///
		QTimeAlone93 ///
		QTimeFamily93 ///
		QTimeColleague93 ///
		QTimeOthers93 ///
		QTimeCompUse93 ///
		QCompUse93 ///
		QCompUseShopping93 ///
		QCompUseLeisure93 ///
		QCompUseCom93 ///
		QCompUseComFam93 ///
		QCompUseComFrnd93 ///
		QCompUseComOthers93 ///
		QCompUseOthers93 ///
		QTime94 ///
		QActType94 ///
		QTimeAlone94 ///
		QTimeFamily94 ///
		QTimeColleague94 ///
		QTimeOthers94 ///
		QTimeCompUse94 ///
		QCompUse94 ///
		QCompUseShopping94 ///
		QCompUseLeisure94 ///
		QCompUseCom94 ///
		QCompUseComFam94 ///
		QCompUseComFrnd94 ///
		QCompUseComOthers94 ///
		QCompUseOthers94 ///
		QTime95 ///
		QActType95 ///
		QTimeAlone95 ///
		QTimeFamily95 ///
		QTimeColleague95 ///
		QTimeOthers95 ///
		QTimeCompUse95 ///
		QCompUse95 ///
		QCompUseShopping95 ///
		QCompUseLeisure95 ///
		QCompUseCom95 ///
		QCompUseComFam95 ///
		QCompUseComFrnd95 ///
		QCompUseComOthers95 ///
		QCompUseOthers95 ///
		QTime96 ///
		QActType96 ///
		QTimeAlone96 ///
		QTimeFamily96 ///
		QTimeColleague96 ///
		QTimeOthers96 ///
		QTimeCompUse96 ///
		QCompUse96 ///
		QCompUseShopping96 ///
		QCompUseLeisure96 ///
		QCompUseCom96 ///
		QCompUseComFam96 ///
		QCompUseComFrnd96 ///
		QCompUseComOthers96 ///
		QCompUseOthers96 ///
		QTimeS1 ///
		QActTypeS1 ///
		QTimeAloneS1 ///
		QTimeFamilyS1 ///
		QTimeColleagueS1 ///
		QTimeOthersS1 ///
		QTimeCompUseS1 ///
		QCompUseS1 ///
		QCompUseShoppingS1 ///
		QCompUseLeisureS1 ///
		QCompUseComS1 ///
		QCompUseComFamS1 ///
		QCompUseComFrndS1 ///
		QCompUseComOthersS1 ///
		QCompUseOthersS1 ///
		QTimeS2 ///
		QActTypeS2 ///
		QTimeAloneS2 ///
		QTimeFamilyS2 ///
		QTimeColleagueS2 ///
		QTimeOthersS2 ///
		QTimeCompUseS2 ///
		QCompUseS2 ///
		QCompUseShoppingS2 ///
		QCompUseLeisureS2 ///
		QCompUseComS2 ///
		QCompUseComFamS2 ///
		QCompUseComFrndS2 ///
		QCompUseComOthersS2 ///
		QCompUseOthersS2 ///
		QTimeS3 ///
		QActTypeS3 ///
		QTimeAloneS3 ///
		QTimeFamilyS3 ///
		QTimeColleagueS3 ///
		QTimeOthersS3 ///
		QTimeCompUseS3 ///
		QCompUseS3 ///
		QCompUseShoppingS3 ///
		QCompUseLeisureS3 ///
		QCompUseComS3 ///
		QCompUseComFamS3 ///
		QCompUseComFrndS3 ///
		QCompUseComOthersS3 ///
		QCompUseOthersS3 ///
		QTimeS4 ///
		QActTypeS4 ///
		QTimeAloneS4 ///
		QTimeFamilyS4 ///
		QTimeColleagueS4 ///
		QTimeOthersS4 ///
		QTimeCompUseS4 ///
		QCompUseS4 ///
		QCompUseShoppingS4 ///
		QCompUseLeisureS4 ///
		QCompUseComS4 ///
		QCompUseComFamS4 ///
		QCompUseComFrndS4 ///
		QCompUseComOthersS4 ///
		QCompUseOthersS4 ///
		QTimeS5 ///
		QActTypeS5 ///
		QTimeAloneS5 ///
		QTimeFamilyS5 ///
		QTimeColleagueS5 ///
		QTimeOthersS5 ///
		QTimeCompUseS5 ///
		QCompUseS5 ///
		QCompUseShoppingS5 ///
		QCompUseLeisureS5 ///
		QCompUseComS5 ///
		QCompUseComFamS5 ///
		QCompUseComFrndS5 ///
		QCompUseComOthersS5 ///
		QCompUseOthersS5 ///
		QTimeS6 ///
		QActTypeS6 ///
		QTimeAloneS6 ///
		QTimeFamilyS6 ///
		QTimeColleagueS6 ///
		QTimeOthersS6 ///
		QTimeCompUseS6 ///
		QCompUseS6 ///
		QCompUseShoppingS6 ///
		QCompUseLeisureS6 ///
		QCompUseComS6 ///
		QCompUseComFamS6 ///
		QCompUseComFrndS6 ///
		QCompUseComOthersS6 ///
		QCompUseOthersS6 ///
		QTimeS7 ///
		QActTypeS7 ///
		QTimeAloneS7 ///
		QTimeFamilyS7 ///
		QTimeColleagueS7 ///
		QTimeOthersS7 ///
		QTimeCompUseS7 ///
		QCompUseS7 ///
		QCompUseShoppingS7 ///
		QCompUseLeisureS7 ///
		QCompUseComS7 ///
		QCompUseComFamS7 ///
		QCompUseComFrndS7 ///
		QCompUseComOthersS7 ///
		QCompUseOthersS7 ///
		QTimeS8 ///
		QActTypeS8 ///
		QTimeAloneS8 ///
		QTimeFamilyS8 ///
		QTimeColleagueS8 ///
		QTimeOthersS8 ///
		QTimeCompUseS8 ///
		QCompUseS8 ///
		QCompUseShoppingS8 ///
		QCompUseLeisureS8 ///
		QCompUseComS8 ///
		QCompUseComFamS8 ///
		QCompUseComFrndS8 ///
		QCompUseComOthersS8 ///
		QCompUseOthersS8 ///
		QDayOff
