********************************************************************************
* Variable Names of the Anonymous STULA1996
********************************************************************************
local   ListQVars ///
		GvmtStatsCode ///
		KanriCode ///
		SurveyYear ///
		SurveyType ///
		SerialNumRecord ///
		SerialNumHH ///
		SerialNumHHMem ///
		SingleHH ///
		ThreeMajorUrbanArea ///
		QSex ///
		QRelRes ///
		QCAgeRes ///
		QMarStatRes ///
		QEduRes ///
		QCoresFam65Nursing ///
		QLivSepFam65Nursing ///
		QCoresOthersNursing ///
		QLivSepOthersNursing ///
		QNoneNursing ///
		QLivArrChild ///
		QJobStat ///
		QEmpStatX ///
		QEmpStatY ///
		QJobSize ///
		QWorkHoursWeek ///
		QCommuteTime ///
		QJobHolidays ///
		QVacNewYear ///
		QVacGW ///
		QVacSummer ///
		QVacOthers ///
		QVacNone ///	
		QHouseType ///
		QNofRoom ///
		QPrivCar ///
		QHHInc ///
		QUnaccAssignment ///
		QUnaccAssignmentSouse ///
		QUnaccAssignmentParents ///
		QUnaccAssignmentChild ///
		QUnaccAssignmentOthers ///
		QHosp ///
		QHospSpouse ///
		QHospParents ///
		QHospChild ///
		QHospOthers ///
		KSES ///
		KHHType ///
		KDoubleInc ///
		KEduNatYg ///
		KCAgeNatYg ///
		QNofHHpsnOver10 ///
        QNofHHpsnUnder10 ///
        KWeight ///
		QDayWeek ///
		QDayNoteTrip ///
		QDayNotePicnic ///
		QDayNoteCeremony ///
		QDayNoteBusinessTrip ///
		QDayNoteResting ///
		QDayNoteDayoff ///
		QDayNoteOthers ///
		QWeather ///
		QSleepTotal ///
		QSleepAlone ///
		QSleepFamily ///
		QSleepColleague ///
		QSleepOthers ///
		QSleepUK ///
		QPersonalCareTotal ///
		QPersonalCareAlone ///
		QPersonalCareFamily ///
		QPersonalCareColleague ///
		QPersonalCareOthers ///
		QPersonalCareUK ///
		QMealTotal ///
		QMealAlone ///
		QMealFamily ///
		QMeaColleague ///
		QMealOthers ///
		QMealUK ///
		QCommuteTotal ///
		QCommuteAlone ///
		QCommuteFamily ///
		QCommuteColleague ///
		QCommuteOthers ///
		QCommuteUK ///
		QWorkTotal ///
		QWorkAlone ///
		QWorkFamily ///
		QWorkColleague ///
		QWorkOthers ///
		QWorkUK ///
		QSchoolWorkTotal ///
		QSchoolWorkAlone ///
		QSchoolWorkFamily ///
		QSchoolWorkColleague ///
		QSchoolWorkOthers ///
		QSchoolWorkUK ///
		QHousekeepingTotal ///
		QHousekeepingAlone ///
		QHousekeepingFamily ///
		QHousekeepingColleague ///
		QHousekeepingOthers ///
		QHousekeepingUK ///
		QNursingTotal ///
		QNursingAlone ///
		QNursingFamily ///
		QNursingColleague ///
		QNursingOthers ///
		QNursingUK ///
		QChildcareTotal ///
		QChildcareAlone ///
		QChildcareFamily ///
		QChildcareColleague ///
		QChildcareOthers ///
		QChildcareUK ///
		QShoppingTotal ///
		QShoppingAlone ///
		QShoppingFamily ///
		QShoppingColleague ///
		QShoppingOthers ///
		QShoppingUK ///
		QTravelTotal ///
		QTravelAlone ///
		QTravelFamily ///
		QTravelColleague ///
		QTravelOthers ///
		QTravelUK ///
		QTVRadioNewsMagTotal ///
		QTVRadioNewsMagAlone ///
		QTVRadioNewsMagFamily ///
		QTVRadioNewsMagColleague ///
		QTVRadioNewsMagOthers ///
		QTVRadioNewsMagUK ///
		QRestingTotal ///
		QRestingAlone ///
		QRestingFamily ///
		QRestingColleague ///
		QRestingOthers ///
		QRestingUK ///
		QStudyTotal ///
		QStudyAlone ///
		QStudyFamily ///
		QStudyColleague ///
		QStudyOthers ///
		QStudyUK ///
		QLeisureTotal ///
		QLeisureAlone ///
		QLeisureFamily ///
		QLeisureColleague ///
		QLeisureOthers ///
		QLeisureUK ///
		QSportsTotal ///
		QSportsAlone ///
		QSportsFamily ///
		QSportsColleague ///
		QSportsOthers ///
		QSportsUK ///
		QSocialActTotal ///
		QSocialActAlone ///
		QSocialActFamily ///
		QSocialActColleague ///
		QSocialActOthers ///
		QSocialActUK ///
		QSocialLifeTotal ///
		QSocialLifeAlone ///
		QSocialLifeFamily ///
		QSocialLifeColleague ///
		QSocialLifeOthers ///
		QSocialLifeUK ///
		QMedTreatTotal ///
		QMedTreatAlone ///
		QMedTreatFamily ///
		QMedTreatColleague ///
		QMedTreatOthers ///
		QMedTreatUK ///
		QOthersTotal ///
		QOthersAlone ///
		QOthersFamily ///
		QOthersColleague ///
		QOthersOthers ///
		QOthersUK ///
		QFstActTotal ///
		QFstActAlone ///
		QFstActFamily ///
		QFstActColleague ///
		QFstActOthers ///
		QFstActUK ///
		QSndActTotal ///
		QSndActAlone ///
		QSndActFamily ///
		QSndActColleague ///
		QSndActOthers ///
		QSndActUK ///
		QTrdActTotal ///
		QTrdActAlone ///
		QTrdActFamily ///
		QTrdActColleague ///
		QTrdActOthers ///
		QTrdActUK ///
		QTime1 ///
		QActType1 ///
		QTimeAlone1 ///
		QTimeFamily1 ///
		QTimeColleague1 ///
		QTimeOthers1 ///
		QTime2 ///
		QActType2 ///
		QTimeAlone2 ///
		QTimeFamily2 ///
		QTimeColleague2 ///
		QTimeOthers2 ///
		QTime3 ///
		QActType3 ///
		QTimeAlone3 ///
		QTimeFamily3 ///
		QTimeColleague3 ///
		QTimeOthers3 ///
		QTime4 ///
		QActType4 ///
		QTimeAlone4 ///
		QTimeFamily4 ///
		QTimeColleague4 ///
		QTimeOthers4 ///
		QTime5 ///
		QActType5 ///
		QTimeAlone5 ///
		QTimeFamily5 ///
		QTimeColleague5 ///
		QTimeOthers5 ///
		QTime6 ///
		QActType6 ///
		QTimeAlone6 ///
		QTimeFamily6 ///
		QTimeColleague6 ///
		QTimeOthers6 ///
		QTime7 ///
		QActType7 ///
		QTimeAlone7 ///
		QTimeFamily7 ///
		QTimeColleague7 ///
		QTimeOthers7 ///
		QTime8 ///
		QActType8 ///
		QTimeAlone8 ///
		QTimeFamily8 ///
		QTimeColleague8 ///
		QTimeOthers8 ///
		QTime9 ///
		QActType9 ///
		QTimeAlone9 ///
		QTimeFamily9 ///
		QTimeColleague9 ///
		QTimeOthers9 ///
		QTime10 ///
		QActType10 ///
		QTimeAlone10 ///
		QTimeFamily10 ///
		QTimeColleague10 ///
		QTimeOthers10 ///
		QTime11 ///
		QActType11 ///
		QTimeAlone11 ///
		QTimeFamily11 ///
		QTimeColleague11 ///
		QTimeOthers11 ///
		QTime12 ///
		QActType12 ///
		QTimeAlone12 ///
		QTimeFamily12 ///
		QTimeColleague12 ///
		QTimeOthers12 ///
		QTime13 ///
		QActType13 ///
		QTimeAlone13 ///
		QTimeFamily13 ///
		QTimeColleague13 ///
		QTimeOthers13 ///
		QTime14 ///
		QActType14 ///
		QTimeAlone14 ///
		QTimeFamily14 ///
		QTimeColleague14 ///
		QTimeOthers14 ///
		QTime15 ///
		QActType15 ///
		QTimeAlone15 ///
		QTimeFamily15 ///
		QTimeColleague15 ///
		QTimeOthers15 ///
		QTime16 ///
		QActType16 ///
		QTimeAlone16 ///
		QTimeFamily16 ///
		QTimeColleague16 ///
		QTimeOthers16 ///
		QTime17 ///
		QActType17 ///
		QTimeAlone17 ///
		QTimeFamily17 ///
		QTimeColleague17 ///
		QTimeOthers17 ///
		QTime18 ///
		QActType18 ///
		QTimeAlone18 ///
		QTimeFamily18 ///
		QTimeColleague18 ///
		QTimeOthers18 ///
		QTime19 ///
		QActType19 ///
		QTimeAlone19 ///
		QTimeFamily19 ///
		QTimeColleague19 ///
		QTimeOthers19 ///
		QTime20 ///
		QActType20 ///
		QTimeAlone20 ///
		QTimeFamily20 ///
		QTimeColleague20 ///
		QTimeOthers20 ///
		QTime21 ///
		QActType21 ///
		QTimeAlone21 ///
		QTimeFamily21 ///
		QTimeColleague21 ///
		QTimeOthers21 ///
		QTime22 ///
		QActType22 ///
		QTimeAlone22 ///
		QTimeFamily22 ///
		QTimeColleague22 ///
		QTimeOthers22 ///
		QTime23 ///
		QActType23 ///
		QTimeAlone23 ///
		QTimeFamily23 ///
		QTimeColleague23 ///
		QTimeOthers23 ///
		QTime24 ///
		QActType24 ///
		QTimeAlone24 ///
		QTimeFamily24 ///
		QTimeColleague24 ///
		QTimeOthers24 ///
		QTime25 ///
		QActType25 ///
		QTimeAlone25 ///
		QTimeFamily25 ///
		QTimeColleague25 ///
		QTimeOthers25 ///
		QTime26 ///
		QActType26 ///
		QTimeAlone26 ///
		QTimeFamily26 ///
		QTimeColleague26 ///
		QTimeOthers26 ///
		QTime27 ///
		QActType27 ///
		QTimeAlone27 ///
		QTimeFamily27 ///
		QTimeColleague27 ///
		QTimeOthers27 ///
		QTime28 ///
		QActType28 ///
		QTimeAlone28 ///
		QTimeFamily28 ///
		QTimeColleague28 ///
		QTimeOthers28 ///
		QTime29 ///
		QActType29 ///
		QTimeAlone29 ///
		QTimeFamily29 ///
		QTimeColleague29 ///
		QTimeOthers29 ///
		QTime30 ///
		QActType30 ///
		QTimeAlone30 ///
		QTimeFamily30 ///
		QTimeColleague30 ///
		QTimeOthers30 ///
		QTime31 ///
		QActType31 ///
		QTimeAlone31 ///
		QTimeFamily31 ///
		QTimeColleague31 ///
		QTimeOthers31 ///
		QTime32 ///
		QActType32 ///
		QTimeAlone32 ///
		QTimeFamily32 ///
		QTimeColleague32 ///
		QTimeOthers32 ///
		QTime33 ///
		QActType33 ///
		QTimeAlone33 ///
		QTimeFamily33 ///
		QTimeColleague33 ///
		QTimeOthers33 ///
		QTime34 ///
		QActType34 ///
		QTimeAlone34 ///
		QTimeFamily34 ///
		QTimeColleague34 ///
		QTimeOthers34 ///
		QTime35 ///
		QActType35 ///
		QTimeAlone35 ///
		QTimeFamily35 ///
		QTimeColleague35 ///
		QTimeOthers35 ///
		QTime36 ///
		QActType36 ///
		QTimeAlone36 ///
		QTimeFamily36 ///
		QTimeColleague36 ///
		QTimeOthers36 ///
		QTime37 ///
		QActType37 ///
		QTimeAlone37 ///
		QTimeFamily37 ///
		QTimeColleague37 ///
		QTimeOthers37 ///
		QTime38 ///
		QActType38 ///
		QTimeAlone38 ///
		QTimeFamily38 ///
		QTimeColleague38 ///
		QTimeOthers38 ///
		QTime39 ///
		QActType39 ///
		QTimeAlone39 ///
		QTimeFamily39 ///
		QTimeColleague39 ///
		QTimeOthers39 ///
		QTime40 ///
		QActType40 ///
		QTimeAlone40 ///
		QTimeFamily40 ///
		QTimeColleague40 ///
		QTimeOthers40 ///
		QTime41 ///
		QActType41 ///
		QTimeAlone41 ///
		QTimeFamily41 ///
		QTimeColleague41 ///
		QTimeOthers41 ///
		QTime42 ///
		QActType42 ///
		QTimeAlone42 ///
		QTimeFamily42 ///
		QTimeColleague42 ///
		QTimeOthers42 ///
		QTime43 ///
		QActType43 ///
		QTimeAlone43 ///
		QTimeFamily43 ///
		QTimeColleague43 ///
		QTimeOthers43 ///
		QTime44 ///
		QActType44 ///
		QTimeAlone44 ///
		QTimeFamily44 ///
		QTimeColleague44 ///
		QTimeOthers44 ///
		QTime45 ///
		QActType45 ///
		QTimeAlone45 ///
		QTimeFamily45 ///
		QTimeColleague45 ///
		QTimeOthers45 ///
		QTime46 ///
		QActType46 ///
		QTimeAlone46 ///
		QTimeFamily46 ///
		QTimeColleague46 ///
		QTimeOthers46 ///
		QTime47 ///
		QActType47 ///
		QTimeAlone47 ///
		QTimeFamily47 ///
		QTimeColleague47 ///
		QTimeOthers47 ///
		QTime48 ///
		QActType48 ///
		QTimeAlone48 ///
		QTimeFamily48 ///
		QTimeColleague48 ///
		QTimeOthers48 ///
		QTime49 ///
		QActType49 ///
		QTimeAlone49 ///
		QTimeFamily49 ///
		QTimeColleague49 ///
		QTimeOthers49 ///
		QTime50 ///
		QActType50 ///
		QTimeAlone50 ///
		QTimeFamily50 ///
		QTimeColleague50 ///
		QTimeOthers50 ///
		QTime51 ///
		QActType51 ///
		QTimeAlone51 ///
		QTimeFamily51 ///
		QTimeColleague51 ///
		QTimeOthers51 ///
		QTime52 ///
		QActType52 ///
		QTimeAlone52 ///
		QTimeFamily52 ///
		QTimeColleague52 ///
		QTimeOthers52 ///
		QTime53 ///
		QActType53 ///
		QTimeAlone53 ///
		QTimeFamily53 ///
		QTimeColleague53 ///
		QTimeOthers53 ///
		QTime54 ///
		QActType54 ///
		QTimeAlone54 ///
		QTimeFamily54 ///
		QTimeColleague54 ///
		QTimeOthers54 ///
		QTime55 ///
		QActType55 ///
		QTimeAlone55 ///
		QTimeFamily55 ///
		QTimeColleague55 ///
		QTimeOthers55 ///
		QTime56 ///
		QActType56 ///
		QTimeAlone56 ///
		QTimeFamily56 ///
		QTimeColleague56 ///
		QTimeOthers56 ///
		QTime57 ///
		QActType57 ///
		QTimeAlone57 ///
		QTimeFamily57 ///
		QTimeColleague57 ///
		QTimeOthers57 ///
		QTime58 ///
		QActType58 ///
		QTimeAlone58 ///
		QTimeFamily58 ///
		QTimeColleague58 ///
		QTimeOthers58 ///
		QTime59 ///
		QActType59 ///
		QTimeAlone59 ///
		QTimeFamily59 ///
		QTimeColleague59 ///
		QTimeOthers59 ///
		QTime60 ///
		QActType60 ///
		QTimeAlone60 ///
		QTimeFamily60 ///
		QTimeColleague60 ///
		QTimeOthers60 ///
		QTime61 ///
		QActType61 ///
		QTimeAlone61 ///
		QTimeFamily61 ///
		QTimeColleague61 ///
		QTimeOthers61 ///
		QTime62 ///
		QActType62 ///
		QTimeAlone62 ///
		QTimeFamily62 ///
		QTimeColleague62 ///
		QTimeOthers62 ///
		QTime63 ///
		QActType63 ///
		QTimeAlone63 ///
		QTimeFamily63 ///
		QTimeColleague63 ///
		QTimeOthers63 ///
		QTime64 ///
		QActType64 ///
		QTimeAlone64 ///
		QTimeFamily64 ///
		QTimeColleague64 ///
		QTimeOthers64 ///
		QTime65 ///
		QActType65 ///
		QTimeAlone65 ///
		QTimeFamily65 ///
		QTimeColleague65 ///
		QTimeOthers65 ///
		QTime66 ///
		QActType66 ///
		QTimeAlone66 ///
		QTimeFamily66 ///
		QTimeColleague66 ///
		QTimeOthers66 ///
		QTime67 ///
		QActType67 ///
		QTimeAlone67 ///
		QTimeFamily67 ///
		QTimeColleague67 ///
		QTimeOthers67 ///
		QTime68 ///
		QActType68 ///
		QTimeAlone68 ///
		QTimeFamily68 ///
		QTimeColleague68 ///
		QTimeOthers68 ///
		QTime69 ///
		QActType69 ///
		QTimeAlone69 ///
		QTimeFamily69 ///
		QTimeColleague69 ///
		QTimeOthers69 ///
		QTime70 ///
		QActType70 ///
		QTimeAlone70 ///
		QTimeFamily70 ///
		QTimeColleague70 ///
		QTimeOthers70 ///
		QTime71 ///
		QActType71 ///
		QTimeAlone71 ///
		QTimeFamily71 ///
		QTimeColleague71 ///
		QTimeOthers71 ///
		QTime72 ///
		QActType72 ///
		QTimeAlone72 ///
		QTimeFamily72 ///
		QTimeColleague72 ///
		QTimeOthers72 ///
		QTime73 ///
		QActType73 ///
		QTimeAlone73 ///
		QTimeFamily73 ///
		QTimeColleague73 ///
		QTimeOthers73 ///
		QTime74 ///
		QActType74 ///
		QTimeAlone74 ///
		QTimeFamily74 ///
		QTimeColleague74 ///
		QTimeOthers74 ///
		QTime75 ///
		QActType75 ///
		QTimeAlone75 ///
		QTimeFamily75 ///
		QTimeColleague75 ///
		QTimeOthers75 ///
		QTime76 ///
		QActType76 ///
		QTimeAlone76 ///
		QTimeFamily76 ///
		QTimeColleague76 ///
		QTimeOthers76 ///
		QTime77 ///
		QActType77 ///
		QTimeAlone77 ///
		QTimeFamily77 ///
		QTimeColleague77 ///
		QTimeOthers77 ///
		QTime78 ///
		QActType78 ///
		QTimeAlone78 ///
		QTimeFamily78 ///
		QTimeColleague78 ///
		QTimeOthers78 ///
		QTime79 ///
		QActType79 ///
		QTimeAlone79 ///
		QTimeFamily79 ///
		QTimeColleague79 ///
		QTimeOthers79 ///
		QTime80 ///
		QActType80 ///
		QTimeAlone80 ///
		QTimeFamily80 ///
		QTimeColleague80 ///
		QTimeOthers80 ///
		QTime81 ///
		QActType81 ///
		QTimeAlone81 ///
		QTimeFamily81 ///
		QTimeColleague81 ///
		QTimeOthers81 ///
		QTime82 ///
		QActType82 ///
		QTimeAlone82 ///
		QTimeFamily82 ///
		QTimeColleague82 ///
		QTimeOthers82 ///
		QTime83 ///
		QActType83 ///
		QTimeAlone83 ///
		QTimeFamily83 ///
		QTimeColleague83 ///
		QTimeOthers83 ///
		QTime84 ///
		QActType84 ///
		QTimeAlone84 ///
		QTimeFamily84 ///
		QTimeColleague84 ///
		QTimeOthers84 ///
		QTime85 ///
		QActType85 ///
		QTimeAlone85 ///
		QTimeFamily85 ///
		QTimeColleague85 ///
		QTimeOthers85 ///
		QTime86 ///
		QActType86 ///
		QTimeAlone86 ///
		QTimeFamily86 ///
		QTimeColleague86 ///
		QTimeOthers86 ///
		QTime87 ///
		QActType87 ///
		QTimeAlone87 ///
		QTimeFamily87 ///
		QTimeColleague87 ///
		QTimeOthers87 ///
		QTime88 ///
		QActType88 ///
		QTimeAlone88 ///
		QTimeFamily88 ///
		QTimeColleague88 ///
		QTimeOthers88 ///
		QTime89 ///
		QActType89 ///
		QTimeAlone89 ///
		QTimeFamily89 ///
		QTimeColleague89 ///
		QTimeOthers89 ///
		QTime90 ///
		QActType90 ///
		QTimeAlone90 ///
		QTimeFamily90 ///
		QTimeColleague90 ///
		QTimeOthers90 ///
		QTime91 ///
		QActType91 ///
		QTimeAlone91 ///
		QTimeFamily91 ///
		QTimeColleague91 ///
		QTimeOthers91 ///
		QTime92 ///
		QActType92 ///
		QTimeAlone92 ///
		QTimeFamily92 ///
		QTimeColleague92 ///
		QTimeOthers92 ///
		QTime93 ///
		QActType93 ///
		QTimeAlone93 ///
		QTimeFamily93 ///
		QTimeColleague93 ///
		QTimeOthers93 ///
		QTime94 ///
		QActType94 ///
		QTimeAlone94 ///
		QTimeFamily94 ///
		QTimeColleague94 ///
		QTimeOthers94 ///
		QTime95 ///
		QActType95 ///
		QTimeAlone95 ///
		QTimeFamily95 ///
		QTimeColleague95 ///
		QTimeOthers95 ///
		QTime96 ///
		QActType96 ///
		QTimeAlone96 ///
		QTimeFamily96 ///
		QTimeColleague96 ///
		QTimeOthers96

