********************************************************************************
* Variable Names of the Anonymous STULA1991
********************************************************************************
local	ListQVars ///
		GvmtStatsCode ///
		KanriCode ///
		SurveyYear ///
		SurveyType ///
		SerialNumRecord ///
		SerialNumHH ///
		SerialNumHHMem ///
		ThreeMajorUrbanArea ///
		QSex ///
		QRelRes ///
		QCAgeRes ///
		QMarStatRes ///
		QEduRes ///
		QFamCare ///
		QJobStat ///
		QEmpStat ///
		QJobSize ///
		QWorkHoursWeek ///
		QJobHolidays ///
		QVac ///
		QVacTim1 ///
		QVacPur1 ///
		QVacTim2 ///
		QVacPur2 ///
		QVacTim3 ///
		QVacPur3 ///
		QVacTim4 ///
		QVacPur4 ///
		QHouseType ///
		QNofRoom ///
		QPrivCar ///
		QHHInc ///
		KSES ///
		KHHType ///
		KDoubleInc ///
		KCAgeNatYg ///
		KWeight ///
		QDayWeek ///
		QDayNote ///
		QSleepTotal ///
		QPersonalCareTotal ///
		QMealTotal ///
		QCommuteTotal ///
		QWorkTotal ///
		QSchoolWorkTotal ///
		QHousekeepingTotal ///
		QNursingTotal ///
		QChildcareTotal ///
		QShoppingTotal ///
		QTravelTotal ///
		QTVRadioNewsMagTotal ///
		QRestingTotal ///
		QStudyTotal ///
		QLeisureTotal ///
		QSportsTotal ///
		QSocialActTotal ///
		QSocialLifeTotal ///
		QMedTreatTotal ///
		QOthersTotal ///
		QFstActTotal ///
		QSndActTotal ///
		QTrdActTotal ///
		QNofCellAct ///
		QTimeAct1 ///
		QActType1 ///
		QTimeAct2 ///
		QActType2 ///
		QTimeAct3 ///
		QActType3 ///
		QTimeAct4 ///
		QActType4 ///
		QTimeAct5 ///
		QActType5 ///
		QTimeAct6 ///
		QActType6 ///
		QTimeAct7 ///
		QActType7 ///
		QTimeAct8 ///
		QActType8 ///
		QTimeAct9 ///
		QActType9 ///
		QTimeAct10 ///
		QActType10 ///
		QTimeAct11 ///
		QActType11 ///
		QTimeAct12 ///
		QActType12 ///
		QTimeAct13 ///
		QActType13 ///
		QTimeAct14 ///
		QActType14 ///
		QTimeAct15 ///
		QActType15 ///
		QTimeAct16 ///
		QActType16 ///
		QTimeAct17 ///
		QActType17 ///
		QTimeAct18 ///
		QActType18 ///
		QTimeAct19 ///
		QActType19 ///
		QTimeAct20 ///
		QActType20 ///
		QTimeAct21 ///
		QActType21 ///
		QTimeAct22 ///
		QActType22 ///
		QTimeAct23 ///
		QActType23 ///
		QTimeAct24 ///
		QActType24 ///
		QTimeAct25 ///
		QActType25 ///
		QTimeAct26 ///
		QActType26 ///
		QTimeAct27 ///
		QActType27 ///
		QTimeAct28 ///
		QActType28 ///
		QTimeAct29 ///
		QActType29 ///
		QTimeAct30 ///
		QActType30 ///
		QTimeAct31 ///
		QActType31 ///
		QTimeAct32 ///
		QActType32 ///
		QTimeAct33 ///
		QActType33 ///
		QTimeAct34 ///
		QActType34 ///
		QTimeAct35 ///
		QActType35 ///
		QTimeAct36 ///
		QActType36 ///
		QTimeAct37 ///
		QActType37 ///
		QTimeAct38 ///
		QActType38 ///
		QTimeAct39 ///
		QActType39 ///
		QTimeAct40 ///
		QActType40 ///
		QTimeAct41 ///
		QActType41 ///
		QTimeAct42 ///
		QActType42 ///
		QTimeAct43 ///
		QActType43 ///
		QTimeAct44 ///
		QActType44 ///
		QTimeAct45 ///
		QActType45 ///
		QTimeAct46 ///
		QActType46 ///
		QTimeAct47 ///
		QActType47 ///
		QTimeAct48 ///
		QActType48 ///
		QTimeAct49 ///
		QActType49 ///
		QTimeAct50 ///
		QActType50 ///
		QTimeAct51 ///
		QActType51 ///
		QTimeAct52 ///
		QActType52 ///
		QTimeAct53 ///
		QActType53 ///
		QTimeAct54 ///
		QActType54 ///
		QTimeAct55 ///
		QActType55 ///
		QTimeAct56 ///
		QActType56 ///
		QTimeAct57 ///
		QActType57 ///
		QTimeAct58 ///
		QActType58 ///
		QTimeAct59 ///
		QActType59 ///
		QTimeAct60 ///
		QActType60 ///
		QTimeAct61 ///
		QActType61 ///
		QTimeAct62 ///
		QActType62 ///
		QTimeAct63 ///
		QActType63 ///
		QTimeAct64 ///
		QActType64 ///
		QTimeAct65 ///
		QActType65 ///
		QTimeAct66 ///
		QActType66 ///
		QTimeAct67 ///
		QActType67 ///
		QTimeAct68 ///
		QActType68 ///
		QTimeAct69 ///
		QActType69 ///
		QTimeAct70 ///
		QActType70 ///
		QTimeAct71 ///
		QActType71 ///
		QTimeAct72 ///
		QActType72 ///
		QTimeAct73 ///
		QActType73 ///
		QTimeAct74 ///
		QActType74 ///
		QTimeAct75 ///
		QActType75 ///
		QTimeAct76 ///
		QActType76 ///
		QTimeAct77 ///
		QActType77 ///
		QTimeAct78 ///
		QActType78 ///
		QTimeAct79 ///
		QActType79 ///
		QTimeAct80 ///
		QActType80 ///
		QTimeAct81 ///
		QActType81 ///
		QTimeAct82 ///
		QActType82 ///
		QTimeAct83 ///
		QActType83 ///
		QTimeAct84 ///
		QActType84 ///
		QTimeAct85 ///
		QActType85 ///
		QTimeAct86 ///
		QActType86 ///
		QTimeAct87 ///
		QActType87 ///
		QTimeAct88 ///
		QActType88 ///
		QTimeAct89 ///
		QActType89 ///
		QTimeAct90 ///
		QActType90 ///
		QTimeAct91 ///
		QActType91 ///
		QTimeAct92 ///
		QActType92 ///
		QTimeAct93 ///
		QActType93 ///
		QTimeAct94 ///
		QActType94 ///
		QTimeAct95 ///
		QActType95 ///
		QTimeAct96 ///
		QActType96
