********************************************************************************
* The list of the MTUS harmonized variables
*	Harmonized Episode Files (HEF)
********************************************************************************

local Vars2Keep ///
	country ///
	survey ///
	swave ///
	msamp ///
	hldid ///
	persid ///
	id ///
	parntid1 ///
	parntid2 ///
	partid ///
	day ///
	month ///
	year ///
	diary ///
	nowght ///
	hhldsize ///
	hhtype ///
	nchild ///
	agekidx ///
	agekid2 ///
	incorig ///
	income ///
	ownhome ///
	urban ///
	computer ///
	vehicle ///
	sex ///
	age ///
	famstat ///
	singpar ///
	relrefp ///
	civstat ///
	cohab ///
	citizen ///
	empstat ///
	emp ///
	unemp ///
	student ///
	retired ///
	empsp ///
	wrkhrs ///
	empinclm ///
	occupo ///
	isco1 ///
	sector ///
	educa ///
	edcat ///
	rushed ///
	health ///
	carer ///
	disab ///
	ocombwt ///
	propwt ///
	sleep ///
	eatdrink ///
	selfcare ///
	paidwork ///
	educatn ///
	foodprep ///
	cleanetc ///
	maintain ///
	shopserv ///
	garden ///
	petcare ///
	eldcare ///
	pkidcare ///
	ikidcare ///
	religion ///
	volorgwk ///
	commute ///
	travel ///
	sportex ///
	TVradio ///
	read ///
	compint ///
	goout ///
	leisure ///
	missing ///
	sick_jp ///
	act_short*
